2wtrade-pay/modules/report/controllers/ValidateFinanceController.php
<?php
namespace app\modules\report\controllers;

use app\components\web\Controller;
use app\helpers\Utils;
use app\modules\order\models\Order;
use app\modules\report\components\ReportFormValidateFinance;
use app\components\filters\AjaxFilter;
use app\modules\report\models\ReportValidateFinance;
use app\modules\report\models\ReportValidateFinanceData;
use Yii;
use yii\helpers\Url;

/**
 * Class ValidateFinanceController
 * @package app\modules\report\controllers
 */
class ValidateFinanceController extends Controller
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'ajax' => [
                'class' => AjaxFilter::className(),
                'only' => [
                    'load',
                    'parse'
                ],
            ]
        ];
    }

    /**
     * @var ReportFormValidateFinance
     */
    public $reportForm;

    /**
     * @var ReportValidateFinance
     */
    public $reportModel;


    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        $this->reportForm = new ReportFormValidateFinance();
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionStatus($id = null)
    {
        $reportValidateFinance = ReportValidateFinance::findOne($id);

        if ($reportValidateFinance) {

            $statusMap = json_decode($reportValidateFinance->status_map, true);
            $map = [];
            $post = Yii::$app->request->post('satatus');
            if (isset($statusMap['fileStatus'])) {
                $i = 0;
                foreach ($statusMap['fileStatus'] as $fileStatus) {
                    $map[$fileStatus] = $post[$i] ?? 0;
                    $i++;
                }
            }
            $statusMap['map'] = $map;

            $reportValidateFinance->status_map = json_encode($statusMap);
            $reportValidateFinance->save(false, ['status_map']);

            $dataToSave = ReportValidateFinanceData::findAll(['file_id' => $id]);

            foreach ($dataToSave as $data) {

                if (!isset($map[$data->status_file])) {
                    $data->error = $data->error . ' ' . Yii::t('common', 'Статус не найден');
                } else {
                    if ((int)$data->status == (int)$map[$data->status_file]) {
                        // статус не менялся
                    } else {
                        $order = Order::findOne($data->order_id);
                        if ($order) {
                            if ($order->canChangeStatusTo((int)$map[$data->status_file])) {
                                // статус можно поменять
                            } else {
                                $data->error = $data->error . ' ' . Yii::t('common', 'Неразрешенное значение статуса') . ' (' . $order->status_id . '->' . (int)$map[$data->status_file] . ')';
                            }
                        }
                    }
                }
                $data->save(false, ['error']);
            }

            return $this->redirect(Url::toRoute('index?file=' . $id));
        } else {
            return $this->redirect(Url::toRoute('index'));
        }
    }

    /**
     * @param integer $file
     * @return string
     */
    public function actionIndex($file = null)
    {
        $reportValidateFinance = ReportValidateFinance::findOne($file);

        if ($reportValidateFinance) {
            $dataArray = $this->reportForm->getHistoryOne($file);
            return $this->render('index', [
                'reportForm' => $this->reportForm,
                'dataHistory' => $dataArray['dataHistory'],
                'sumsArray' => $dataArray['sumsArray'],
                'file' => $file,
                'model' => $reportValidateFinance,
            ]);
        } else {
            $dataHistory = $this->reportForm->apply(Yii::$app->request->queryParams);
            return $this->render('index', [
                'reportForm' => $this->reportForm,
                'dataHistory' => $dataHistory,
                'file' => $file,
            ]);
        }
    }

    /**
     * @return array
     */
    public function actionLoad()
    {
        if ($this->reportForm->upload()) {
            return [
                'status' => 'success',
                'file' => $this->reportForm->getFileId(),
            ];
        }
        return [
            'status' => 'fail',
            'message' => implode(',', $this->reportForm->getErrorsAsArray())
        ];
    }

    /**
     * @return array
     */
    public function actionParse()
    {
        return $this->reportForm->parse(Yii::$app->request->post('file'), Yii::$app->request->post('currentStr'));
    }


    /**
     * Экспорт в эксель
     */
    public function actionExportToExcel()
    {

        $file = Yii::$app->request->get('file');
        $type = Yii::$app->request->get('type');

        $reportValidateFinance = ReportValidateFinance::findOne($file);

        if ($reportValidateFinance) {
            $dataArray = $this->reportForm->getHistoryOne($file);
            $dataProvider = $dataArray['dataHistory'];

            $excel = new \PHPExcel();
            $sheet = $excel->getSheet(0);
            $sheet->setTitle(Yii::t('common', 'Сверка фин.отчета'));

            $row = 1;
            $sheet->setCellValueByColumnAndRow(0, $row, Yii::t('common', 'Номер заказа'));
            $sheet->setCellValueByColumnAndRow(1, $row, Yii::t('common', 'Номер заказа (файл)'));
            $sheet->setCellValueByColumnAndRow(2, $row, Yii::t('common', 'Трек номер'));
            $sheet->setCellValueByColumnAndRow(3, $row, Yii::t('common', 'Трек номер (файл)'));
            $sheet->setCellValueByColumnAndRow(4, $row, Yii::t('common', 'Процент от заказа для КС'));
            $sheet->setCellValueByColumnAndRow(5, $row, Yii::t('common', 'Процент от заказа для КС (файл)'));
            $sheet->setCellValueByColumnAndRow(6, $row, Yii::t('common', 'Стоимость фулфиллмента'));
            $sheet->setCellValueByColumnAndRow(7, $row, Yii::t('common', 'Стоимость фулфиллмента (файл)'));
            $sheet->setCellValueByColumnAndRow(8, $row, Yii::t('common', 'НДС на доставку'));
            $sheet->setCellValueByColumnAndRow(9, $row, Yii::t('common', 'НДС на доставку (файл)'));
            $sheet->setCellValueByColumnAndRow(10, $row, Yii::t('common', 'НДС на фулфиллмент'));
            $sheet->setCellValueByColumnAndRow(11, $row, Yii::t('common', 'НДС на фулфиллмент (файл)'));
            $sheet->setCellValueByColumnAndRow(12, $row, Yii::t('common', 'Стоимость доставки'));
            $sheet->setCellValueByColumnAndRow(13, $row, Yii::t('common', 'Стоимость доставки (файл)'));
            $sheet->setCellValueByColumnAndRow(14, $row, Yii::t('common', 'Общая сумма'));
            $sheet->setCellValueByColumnAndRow(15, $row, Yii::t('common', 'Общая сумма (файл)'));
            $sheet->setCellValueByColumnAndRow(16, $row, Yii::t('common', 'Статус'));
            $sheet->setCellValueByColumnAndRow(17, $row, Yii::t('common', 'Статус (файл)'));
            if ($type == 'error') {
                $sheet->setCellValueByColumnAndRow(18, $row, Yii::t('common', 'Текст ошибки'));
            }

            $sheet->getStyleByColumnAndRow(0, $row, 18, $row)->getFont()->setBold(true);
            $row++;

            $sum_delivery_cost_percent = 0;
            $sum_delivery_cost_percent_file = 0;
            $sum_fulfillment_cost = 0;
            $sum_fulfillment_cost_file = 0;
            $sum_nds = 0;
            $sum_nds_file = 0;
            $sum_fulfillment_nds = 0;
            $sum_fulfillment_nds_file = 0;
            $sum_delivery_price = 0;
            $sum_delivery_price_file = 0;
            $sum_total_price = 0;
            $sum_total_price_file = 0;
            foreach ($dataProvider->allModels as $item) {
                if ($type == 'correct' && !empty($item['error'])) {
                    continue;
                }
                if ($type == 'error' && empty($item['error'])) {
                    continue;
                }
                $sheet->setCellValueByColumnAndRow(0, $row, $item['order_id']);
                $sheet->setCellValueByColumnAndRow(1, $row, $item['order_id_file']);
                $sheet->setCellValueByColumnAndRow(2, $row, $item['tracking']);
                $sheet->setCellValueByColumnAndRow(3, $row, $item['tracking_file']);
                $sheet->setCellValueByColumnAndRow(4, $row, $item['delivery_cost_percent']);
                $sheet->setCellValueByColumnAndRow(5, $row, $item['delivery_cost_percent_file']);
                $sheet->setCellValueByColumnAndRow(6, $row, $item['fulfillment_cost']);
                $sheet->setCellValueByColumnAndRow(7, $row, $item['fulfillment_cost_file']);
                $sheet->setCellValueByColumnAndRow(8, $row, $item['nds']);
                $sheet->setCellValueByColumnAndRow(9, $row, $item['nds_file']);
                $sheet->setCellValueByColumnAndRow(10, $row, $item['fulfillment_nds']);
                $sheet->setCellValueByColumnAndRow(11, $row, $item['fulfillment_nds_file']);
                $sheet->setCellValueByColumnAndRow(12, $row, $item['delivery_price']);
                $sheet->setCellValueByColumnAndRow(13, $row, $item['delivery_price_file']);
                $sheet->setCellValueByColumnAndRow(14, $row, $item['total_price']);
                $sheet->setCellValueByColumnAndRow(15, $row, $item['total_price_file']);
                $sheet->setCellValueByColumnAndRow(16, $row, $item['status']);
                $sheet->setCellValueByColumnAndRow(17, $row, $item['status_file']);
                if ($type == 'error') {
                    $sheet->setCellValueByColumnAndRow(18, $row, $item['error']);
                }

                $sum_delivery_cost_percent += $item['delivery_cost_percent'];
                $sum_delivery_cost_percent_file += $item['delivery_cost_percent_file'];

2wtrade-pay/modules/report/views/validate-finance/_load-form.php
<?php
use app\widgets\InputGroupFile;
use app\widgets\InputText;
use yii\helpers\Html;
use app\components\widgets\ActiveForm;
use yii\helpers\Url;
use app\widgets\ProgressBar;
use yii\web\View;

/** @var yii\web\View $this */
/** @var app\modules\report\components\ReportFormValidateFinance $reportForm */
/** @var \app\modules\report\models\ReportValidateFinance $reportModel */

$this->registerJs("var I18n = {};", View::POS_HEAD);
$this->registerJs("I18n['Файл обработан'] = '" . Yii::t('common',
        'Файл обработан') . "';", View::POS_HEAD);

?>
<div class="table-responsive padding-20" id="validate-finance">
<?php
$form = ActiveForm::begin([
    'options' => [
        'enctype' => 'multipart/form-data',
    ],
    'action' => Url::to(['validate-finance/load']),
    'method' => 'post',
]); ?>
<div class="row">
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'row_begin')->textInput(['value' => (isset($reportForm->model->row_begin)) ? $reportForm->model->row_begin : 0]) ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_order_id')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_tracking')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_delivery_cost_percent')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_fulfillment_cost')->checkTextInput() ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_nds')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_fulfillment_nds')->checkTextInput() ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_delivery_price')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_total_price')->checkTextInput() ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($reportForm->model, 'cell_status')->checkTextInput() ?>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <?= InputGroupFile::widget([
            'right' => false,
            'input' => InputText::widget([
                'type' => 'file',
                'name' => Html::getInputName($reportForm, 'loadFile'),
                'id' => 'loadFile',
            ]),
        ]) ?>
    </div>
    <div class="col-md-8">
        <?= Html::submitButton(Yii::t('common', 'Отправить'), ['class' => 'btn btn-success']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

<div class="row-with-text-progress margin-top-15" style="display: none;">
    <h5>
        <?= Yii::t('common', 'Обработка файла') ?>
        <span class="pull-right builder-percent">0%</span>
    </h5>
    <?= ProgressBar::widget() ?>
</div>

<div class="row-with-text-finish" style="display: none;">
    <br>
    <br>
    <div class="margin-bottom-15 text-center">
        <a href="#" class="finish-link"><?=Yii::t('common', 'Обработка завершена, перейти к деталям')?></a>
    </div>
</div>

</div>

2wtrade-pay/modules/report/views/validate-finance/_tab-history-one.php
<?php
use app\modules\report\extensions\GridView;
use app\modules\report\components\ReportFormValidateFinance;
use app\widgets\LinkPager;
use app\widgets\ButtonLink;
use app\components\widgets\ActiveForm;
use app\modules\order\models\OrderStatus;
use yii\helpers\Url;
use yii\helpers\Html;

/** @var app\modules\report\components\ReportFormValidateFinance $reportForm */
/** @var yii\data\ArrayDataProvider $dataHistory */
/** @var app\modules\report\models\ReportValidateFinance $model */
/** @var array $sumsArray */
?>

<div class="row">


    <div class="col-md-4">
        <div class="h4"><?= Yii::t('common', 'Итоги') ?></div>


        <table class="table table-report table-striped table-hover table-bordered">
            <tr>
                <th></th>
                <th><?= Yii::t('common', 'База') ?></th>
                <th><?= Yii::t('common', 'Файл') ?></th>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по проценту от заказа для КС') ?></td>
                <td align="right"><?= $sumsArray['sum_delivery_cost_percent'] ?></td>
                <td align="right"><?= $sumsArray['sum_delivery_cost_percent_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по cтоимости фулфиллмента') ?></td>
                <td align="right"><?= $sumsArray['sum_fulfillment_cost'] ?></td>
                <td align="right"><?= $sumsArray['sum_fulfillment_cost_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по НДС на доставку') ?></td>
                <td align="right"><?= $sumsArray['sum_nds'] ?></td>
                <td align="right"><?= $sumsArray['sum_nds_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по НДС на фулфиллмент') ?></td>
                <td align="right"><?= $sumsArray['sum_fulfillment_nds'] ?></td>
                <td align="right"><?= $sumsArray['sum_fulfillment_nds_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по стоимости доставки') ?></td>
                <td align="right"><?= $sumsArray['sum_delivery_price'] ?></td>
                <td align="right"><?= $sumsArray['sum_delivery_price_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Итого по общей сумме') ?></td>
                <td align="right"><?= $sumsArray['sum_total_price'] ?></td>
                <td align="right"><?= $sumsArray['sum_total_price_file'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Всего предупреждений') ?></td>
                <td colspan="2" align="center"><?= $sumsArray['count_warnings'] ?></td>
            </tr>
            <tr>
                <td><?= Yii::t('common', 'Всего ошибок') ?></td>
                <td colspan="2" align="center"><?= $sumsArray['count_errors'] ?></td>
            </tr>
        </table>
    </div>


    <div class="col-md-6">

        <?php if ($model->cell_status): ?>

            <?php
            $form = ActiveForm::begin([
                'action' => Url::to(['validate-finance/status/' . $model->id]),
                'method' => 'post',
            ]); ?>

            <div class="h4"><?= Yii::t('common', 'Соответсвие статусов в файле и наших') ?></div>

            <?php
            $statusMap = json_decode($model->status_map, true);

            $statuses = OrderStatus::find()->collection();

            if (isset($statusMap['fileStatus'])) {

                $i = 0;
                foreach ($statusMap['fileStatus'] as $fileStatus):?>

                    <div class="row">
                        <div class="col-md-4">
                            <?= ($i + 1) . '. ' . $fileStatus ?>
                        </div>
                        <div class="col-md-8">
                            <?= \app\widgets\Select2::widget([
                                'name' => 'satatus[' . $i . ']',
                                'items' => $statuses,
                                'value' => $statusMap['map'][$fileStatus] ?? 0,
                                'prompt' => Yii::t('common', 'Выберите статус')
                            ]) ?>
                        </div>
                    </div>
                    <?php $i++;
                endforeach;
            } else {
                echo Yii::t('common', 'Статусы в файле не найдены');
            }

            ?>
            <br>
            <div>
                <?= Html::submitButton(Yii::t('common', 'Сверить статусы'), ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        <?php endif; ?>
    </div>

    <div class="col-md-2">
        <div class="pull-right">
            <?= Html::a(Yii::t('common', 'Назад'), \yii\helpers\Url::toRoute('/report/validate-finance/index')) ?>
        </div>
    </div>

</div>

<div id="report_export_to_excel" style="margin-right: 210px; position: absolute; right: 20px; top: 15px;">
    <?php echo ButtonLink ::widget([
        "id" => "btn_export_report_to_excel",
        "url" => Url::toRoute(['validate-finance/export-to-excel', 'type' => 'correct'] + Yii::$app->request->queryParams),
        "style" => ButtonLink::STYLE_DEFAULT . " width-200",
        "size" => ButtonLink::SIZE_SMALL,
        "label" => Yii::t("common", "Экспорт в Excel (без ошибок)"),
    ]); ?>
</div>

<div id="report_export_to_excel" style="position: absolute; right: 20px; top: 15px;">
    <?php echo ButtonLink ::widget([
        "id" => "btn_export_report_to_excel",
        "url" => Url::toRoute(['validate-finance/export-to-excel', 'type' => 'error'] + Yii::$app->request->queryParams),
        "style" => ButtonLink::STYLE_DEFAULT . " width-200",
        "size" => ButtonLink::SIZE_SMALL,
        "label" => Yii::t("common", "Экспорт в Excel (ошибки)"),
    ]); ?>
</div>

<div class="table-responsive margin-top-20">
    <?= GridView::widget([
        'layout' => '<div id="report_export_box">{toolbar}</div>{items}<div class="panel-footer clearfix  margin-top-15  padding-right-0">{pager}</div>',
        'dataProvider' => $dataHistory,
        'reportForm' => $reportForm,
        'resizableColumns' => false,
        'showPageSummary' => false,
        'export' => false,
        'tableOptions' => [
            'class' => 'table table-report table-striped table-hover table-bordered',
        ],
        'rowOptions' => function ($model) {
            return ReportFormValidateFinance::check($model);
        },
        'pager' => [
            'class' => 'app\widgets\LinkPager',
            'counterPosition' => LinkPager::COUNTER_POSITION_RIGHT,
        ],
        'columns' => [
            [
                'label' => Yii::t('common', 'Номер заказа'),
                'attribute' => 'order_id',
            ],
            [
                'label' => Yii::t('common', 'Номер заказа (файл)'),
                'attribute' => 'order_id_file',
            ],
            [
                'label' => Yii::t('common', 'Трек номер'),
                'attribute' => 'tracking',
            ],
            [
                'label' => Yii::t('common', 'Трек номер (файл)'),
                'attribute' => 'tracking_file',
            ],
            [
                'label' => Yii::t('common', 'Процент от заказа для КС'),
                'attribute' => 'delivery_cost_percent',
                'visible' => $model->cell_delivery_cost_percent
            ],
            [
                'label' => Yii::t('common', 'Процент от заказа для КС (файл)'),
                'attribute' => 'delivery_cost_percent_file',
                'visible' => $model->cell_delivery_cost_percent
            ],
            [
                'label' => Yii::t('common', 'Стоимость фулфиллмента'),
                'attribute' => 'fulfillment_cost',
                'visible' => $model->cell_fulfillment_cost
            ],
            [
                'label' => Yii::t('common', 'Стоимость фулфиллмента (файл)'),
                'attribute' => 'fulfillment_cost_file',
                'visible' => $model->cell_fulfillment_cost
            ],
            [
                'label' => Yii::t('common', 'НДС на доставку'),
                'attribute' => 'nds',
                'visible' => $model->cell_nds
            ],
            [
                'label' => Yii::t('common', 'НДС на доставку (файл)'),
                'attribute' => 'nds_file',
                'visible' => $model->cell_nds
            ],
            [
                'label' => Yii::t('common', 'НДС на фулфиллмент'),
                'attribute' => 'fulfillment_nds',
                'visible' => $model->cell_fulfillment_nds
            ],
            [
                'label' => Yii::t('common', 'НДС на фулфиллмент (файл)'),
                'attribute' => 'fulfillment_nds_file',
                'visible' => $model->cell_fulfillment_nds
            ],
            [
                'label' => Yii::t('common', 'Стоимость доставки'),
                'attribute' => 'delivery_price',
                'visible' => $model->cell_delivery_price
            ],
            [
                'label' => Yii::t('common', 'Стоимость доставки (файл)'),
                'attribute' => 'delivery_price_file',
                'visible' => $model->cell_delivery_price
            ],
            [
                'label' => Yii::t('common', 'Общая сумма'),
                'attribute' => 'total_price',
                'visible' => $model->cell_total_price,
            ],
            [
                'label' => Yii::t('common', 'Общая сумма (файл)'),
                'attribute' => 'total_price_file',
                'visible' => $model->cell_total_price,
            ],
            [
                'label' => Yii::t('common', 'Статус'),
                'attribute' => 'status',
                'visible' => $model->cell_status,
            ],
            [
                'label' => Yii::t('common', 'Статус (файл)'),
                'attribute' => 'status_file',
                'visible' => $model->cell_status,
            ],
            [
                'label' => Yii::t('common', 'Текст ошибки'),
                'attribute' => 'error',
                'value' => function ($line) {
                    return trim($line['warning'] . ' ' . $line['error']);
                },
            ],
        ]
    ]) ?>
</div>

2wtrade-pay/modules/report/views/validate-finance/_tab-history.php
<?php
use app\modules\report\extensions\GridView;
use app\modules\report\widgets\ReportFilterValidateFinance;
use yii\helpers\Html;
use yii\helpers\Url;
use app\widgets\LinkPager;

/** @var app\modules\report\components\ReportFormValidateFinance $reportForm */
/** @var yii\data\ArrayDataProvider $dataHistory */
/** @var array $sumsArray */
?>

<?= ReportFilterValidateFinance::widget([
    'reportForm' => $reportForm,
]) ?>

<div class="table-responsive margin-top-20">
    <?= GridView::widget([
        'layout' => '<div id="report_export_box">{toolbar}</div>{items}<div class="panel-footer clearfix  margin-top-15  padding-right-0">{pager}</div>',
        'dataProvider' => $dataHistory,
        'resizableColumns' => false,
        'showPageSummary' => false,
        'export' => false,
        'pager' => [
            'class' => 'app\widgets\LinkPager',
            'counterPosition' => LinkPager::COUNTER_POSITION_RIGHT,
        ],
        'columns' => [
            [
                'value' => function($model) {
                    return Html::a($model['file_name_trim'] . ' ' . $model['created'], Url::to(['validate-finance/index']) . '?file=' . $model['id']);
                },
                'label' => Yii::t('common', 'Отчеты'),
                'format' => 'html',
                'headerOptions' => ['class' => 'text-left']
            ],
        ]
    ]) ?>
</div>

2wtrade-pay/modules/report/views/validate-finance/_tab-load.php
<?php
/** @var app\modules\report\components\ReportFormValidateFinance $reportForm */
?>

<?= $this->render('_load-form', [
    'reportForm' => $reportForm,
]) ?>

2wtrade-pay/modules/report/views/validate-finance/index.php
<?php
use app\modules\report\assets\ReportAsset;
use app\modules\report\assets\ReportValidateFinanceAsset;
use app\widgets\Panel;
use app\widgets\Nav;

/** @var \yii\web\View $this */
/** @var \app\modules\report\components\ReportFormValidateFinance $reportForm */
/** @var yii\data\ArrayDataProvider $dataHistory */
/** @var array $sumsArray */
/** @var string $file */

$this->title = Yii::t('common', 'Сверка финансового отчета');
$this->params['breadcrumbs'][] = ['label' => Yii::t('common', 'Отчеты'), 'url' => '#'];
$this->params['breadcrumbs'][] = ['label' => $this->title];

ReportAsset::register($this);
ReportValidateFinanceAsset::register($this);

if ($file !== null) {
    $view = '_tab-history-one';
    $dataArray = [
        'reportForm' => $reportForm,
        'dataHistory' => $dataHistory,
        'sumsArray' => $sumsArray,
        'model' => $model,
    ];
} else {
    $view = '_tab-history';
    $dataArray = [
        'reportForm' => $reportForm,
        'dataHistory' => $dataHistory,
    ];
}
?>

<?= Panel::widget([
    'nav' => new Nav([
        'tabs' => [
            [
                'label' => Yii::t('common', 'История загрузок'),
                'content' => $this->render($view, $dataArray),
            ],
            [
                'label' => Yii::t('common', 'Загрузка файла'),
                'content' => $this->render('_tab-load', [
                    'reportForm' => $reportForm,
                ]),
            ],
        ]
    ]),
]) ?>